---
- name: Copy Base Files
  hosts: all
  tasks:
    - name: Copy Issue and backup the old
      ansible.builtin.copy:
        src: issue.net
        dest: /etc/issue.net
        owner: root
        group: root
        mode: '0644'
        backup: yes
